### ISSUE TITLE
お寿司おごってください！

### ISSUE THREAD

**Issue by sasarky** [otukutun/CollectionViewSample#1]
🍣

**Comment by otukutun** [comment]
![寿司ゆき:no_dish](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/44.png)

**Comment by sasarky** [comment]
対応ありがとうございました

**Comment by otukutun** [comment]
![寿司ゆき:bye](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/17.png) 

次のissue片付けていきましょ！ 🍣
